name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # runs every day at midnight

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch latest data
        run: npm ci && npm run fetch
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
